baseURL = 'https://example.org/'
languageCode = 'fr-ch'
title = 'Bloglo'
theme = 'gokarna'

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "Moi"
    url = "/about/"
    weight = 2
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/WinnieTheBloue"
    weight = 3
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"

 [[menu.main]]
    identifier = "linkedin"
    url = "https://www.linkedin.com/in/pablo-crotti/"
    weight = 4
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='linkedin'></span>"

  [[menu.main]]
    identifier = "iviou"
    url = "https://iviou.ch"
    weight = 5
    pre = '<svg id="Calque_1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200"><defs><style>.cls-1{fill:"currentColor";fill-rule:evenodd;}</style></defs><path class="cls-1" d="m79.14,86.89c5.7-8.01,14.02-10.9,27.48-11.93l34.27-2.62c15.93-1.22,26.32-.36,32.65,2.01l-25.26-32.39c-14.06-18.01-24.59-18.37-35.41-5.75l-22.37,26.09c-7.78,9.07-11.68,16.33-11.34,24.6h0Zm-5.66-60.48c47.44-3.63,48.17-9.18,10.17,35.12-7.93,9.24-11.82,16.59-11.31,25.06l-16.62-28.79c-10.29-17.82-1.73-29.89,17.77-31.39Z"/><path class="cls-1" d="m120.06,87.96c4.09,8.94,2.43,17.59-3.4,29.76l-14.86,30.99c-6.91,14.4-12.86,22.98-18.06,27.27l40.68-5.69c22.63-3.16,28.2-12.11,22.68-27.79l-11.4-32.42c-3.97-11.28-8.3-18.28-15.64-22.12h0Zm55.21,25.34c-20.58,42.9-16.13,46.3-35.5-8.76-4.04-11.48-8.46-18.53-16.05-22.33h33.25c20.57,0,26.75,13.44,18.3,31.08Z"/><path class="cls-1" d="m98.68,122.86c-9.79-.93-16.45-6.69-24.07-17.83l-19.41-28.37c-9.02-13.19-13.47-22.62-14.59-29.28l-15.41,38.08c-8.58,21.18-3.61,30.48,12.73,33.54l33.78,6.33c11.75,2.2,19.98,1.95,26.98-2.48h0Zm-49.55,35.14c-26.87-39.27-32.03-37.13,25.33-26.36,11.96,2.24,20.28,1.94,27.36-2.73l-16.62,28.79c-10.29,17.82-25.02,16.45-36.07.3Z"/></svg>'



[params]
  # URL for the avatar on homepage
  avatarURL = "https://iviou.ch/img/me.png"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = ""

  socialIcons = [
      {name = "github", url = "https://github.com/WinnieTheBloue"},
      {name = "linkedin", url = "https://www.linkedin.com/in/pablo-crotti/"},
    ]

  # Description to display on homepage
  description = "1, 2, 3... Soleil"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # Display "back to top" button on posts
  ShowBackToTopButton = true

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "gokarna", "hugo"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = "recent"

  # Footer text
  footer = "Bloglo"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = false